[package]
name = "headless"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]

[dependencies]
control = { path = "../control" }
geom = { path = "../geom" }
map_model = { path = "../map_model" }
rand = "0.4"
sim = { path = "../sim" }
structopt = "0.2"
