[package]
name = "headless"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
abstutil = { path = "../abstutil" }
geom = { path = "../geom" }
hyper = "0.13.8"
lazy_static = "1.4.0"
map_model = { path = "../map_model" }
serde = "1.0.116"
sim = { path = "../sim" }
tokio = { version = "0.2.22", features = ["full"] }
url = "2.1.1"
