[package]
name = "headless"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]

[dependencies]
abstutil = { path = "../abstutil" }
cpuprofiler = "0.0.3"
log = "0.4.5"
map_model = { path = "../map_model" }
pretty_assertions = "0.5.1"
sim = { path = "../sim" }
structopt = "0.2"
