[package]
name = "game"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
aabb-quadtree = "0.1.0"
abstutil = { path = "../abstutil" }
built = "0.3.2"
chrono = "0.4.10"
counter = "0.4.3"
downcast-rs = "1.0.4"
ezgui = { path = "../ezgui" }
geom = { path = "../geom" }
kml = { path = "../kml" }
map_model = { path = "../map_model" }
popdat = { path = "../popdat" }
rand = "0.7.0"
rand_xorshift = "0.2.0"
serde = "1.0.98"
serde_derive = "1.0.98"
sim = { path = "../sim" }

[build-dependencies]
built = "0.3.2"
walkdir = "2.2.7"
