[workspace]

members = [
  "abstutil",
  "analyze_code",
  "control",
  "convert_osm",
  "editor",
  "ezgui",
  "geom",
  "gtfs",
  "headless",
  "kml",
  "map_model",
  "playground_gui",
  "sim",
  "tmp_gfx",
]
