[workspace]

members = [
  "abstutil",
  "convert_osm",
  "ezgui",
  "game",
  "geom",
  "gtfs",
  "headless",
  "kml",
  "map_editor",
  "map_model",
  "popdat",
  "precompute",
  "sim",
  "tests",
]
