[workspace]

members = [
  "abstutil",
  "convert_osm",
  "ezgui",
  "fix_map_geom",
  "game",
  "geom",
  "gtfs",
  "headless",
  "kml",
  "map_model",
  "popdat",
  "precompute",
  "sim",
  "synthetic",
  "tests",
  "viewer",
]
