[workspace]

members = [
  "abstutil",
  "analyze_code",
  "benchmark_pathfinding",
  "convert_osm",
  "debug_initialmap",
  "editor",
  "ezgui",
  "geom",
  "gtfs",
  "halloween",
  "headless",
  "kml",
  "map_model",
  "playground_gui",
  "precompute",
  "sim",
  "synthetic",
  "tests",
  "tmp_gfx",
  "viewer",
]
