[package]
name = "updater"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2021"

[dependencies]
abstio = { path = "../abstio" }
abstutil = { path = "../abstutil" }
anyhow = { workspace = true }
flate2 = { workspace = true }
fs-err = { workspace = true }
futures-channel = { workspace = true }
md5 = "0.7.0"
structopt = { workspace = true }
tokio = { workspace = true }
walkdir = "2.3.3"
