[package]
name = "raw_map"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2021"

[dependencies]
abstio = { path = "../abstio" }
abstutil = { path = "../abstutil" }
geom = { path = "../geom" }
serde = "1.0.123"
street_network = { git = "https://github.com/a-b-street/osm2streets" }
strum = "0.21"
strum_macros = "0.21"
