[package]
name = "convert_osm"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]

[dependencies]
abstutil = { path = "../abstutil" }
byteorder = "1.2.1"
geom = { path = "../geom" }
ordered-float = "0.5.0"
osm-xml = "0.5.1"
map_model = { path = "../map_model" }
structopt = "0.2"
