[package]
name = "convert_osm"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
aabb-quadtree = "0.1.0"
abstutil = { path = "../abstutil" }
byteorder = "1.2.1"
geo = "0.11.0"
geojson = "0.14.0"
geom = { path = "../geom" }
gtfs = { path = "../gtfs" }
kml = { path = "../kml" }
osm-xml = "0.6.2"
map_model = { path = "../map_model" }
pretty_assertions = "0.5.1"
structopt = "0.2"
