[package]
name = "convert_osm"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
abstutil = { path = "../abstutil" }
clipping = "0.1.1"
geojson = "0.15.0"
geom = { path = "../geom" }
gtfs = { path = "../gtfs" }
kml = { path = "../kml" }
osm-xml = "0.6.2"
map_model = { path = "../map_model" }
structopt = "0.2.15"
