[package]
name = "convert_osm"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
aabb-quadtree = "0.1.0"
abstutil = { path = "../abstutil" }
byteorder = "1.2.1"
dimensioned = { git = "https://github.com/paholg/dimensioned", rev = "0e1076ebfa5128d1ee544bdc9754c948987b6fe3", features = ["serde"] }
geo = "0.10.2"
geojson = "0.12.0"
geom = { path = "../geom" }
gtfs = { path = "../gtfs" }
kml = { path = "../kml" }
ordered-float = "1.0.1"
osm-xml = "0.5.1"
map_model = { path = "../map_model" }
pretty_assertions = "0.5.1"
sim = { path = "../sim" }
structopt = "0.2"
