[package]
name = "kml"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
abstutil = { path = "../abstutil" }
geom = { path = "../geom" }
quick-xml = "0.13.3"
serde = "1.0.98"
serde_derive = "1.0.98"
