[package]
name = "kml"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
abstutil = { path = "../abstutil" }
geom = { path = "../geom" }
log = "0.4.5"
quick-xml = "0.10.0"
serde = "1.0"
serde_derive = "1.0"
structopt = "0.2"
