[package]
name = "geom"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
aabb-quadtree = "0.1.0"
abstutil = { path = "../abstutil" }
geo = "0.12.0"
ordered-float = "1.0.1"
serde = "1.0.89"
serde_derive = "1.0.89"
