[package]
name = "geom"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]

[dependencies]
aabb-quadtree = "0.1.0"
dimensioned = "0.6.0"
map_model = { path = "../map_model" }
piston2d-graphics = "*"
vecmath = "0.3.1"
