[package]
name = "sim"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]

[dependencies]
control = { path = "../control" }
derivative = "1.0.0"
dimensioned = "0.6.0"
geom = { path = "../geom" }
ezgui = { path = "../ezgui" }
map_model = { path = "../map_model" }
multimap = "0.4.0"
piston2d-graphics = "*"
rand = { version = "0.5.1", features = ["serde1"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
vecmath = "0.3.1"
