[package]
name = "sim"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2021"

[dependencies]
abstio = { path = "../abstio" }
abstutil = { path = "../abstutil" }
anyhow = { workspace = true }
ctrlc = { version = "3.1.7", optional = true }
downcast-rs = "1.2.0"
enum_dispatch = "0.3.5"
geom = { path = "../geom" }
instant = "0.1.7"
libm = "0.2.1"
log = { workspace = true }
map_model = { path = "../map_model" }
rand = { workspace = true }
rand_distr = "0.4.0"
rand_xorshift = { workspace = true }
serde = { workspace = true }
structopt = { workspace = true }
synthpop = { path = "../synthpop" }

[[bin]]
name = "run_scenario"
required-features = ["ctrlc"]
