[package]
name = "sim"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]

[dependencies]
abstutil = { path = "../abstutil" }
backtrace = "0.3.9"
control = { path = "../control" }
derivative = "1.0.0"
dimensioned = { git = "https://github.com/paholg/dimensioned", rev = "0e1076ebfa5128d1ee544bdc9754c948987b6fe3", features = ["serde"] }
flame = "0.2.2"
geom = { path = "../geom" }
lazy_static = "1.1.0"
log = "0.4.5"
map_model = { path = "../map_model" }
more-asserts = "0.2.1"
multimap = "0.4.0"
ordered-float = "0.5.0"
pretty_assertions = "0.5.1"
rand = { version = "0.5.1", features = ["serde1"] }
rayon = "1.0"
serde = "1.0"
serde_derive = "1.0"
structopt = "0.2"
