[package]
name = "sim"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
abstutil = { path = "../abstutil" }
backtrace = "0.3.9"
derivative = "1.0.0"
ezgui = { path = "../ezgui" }
geom = { path = "../geom" }
histogram = "0.6.9"
map_model = { path = "../map_model" }
more-asserts = "0.2.1"
num_cpus = "1.10.0"
pretty_assertions = "0.5.1"
rand = { version = "0.6.5", features = ["serde1"] }
rand_xorshift = "0.1.1"
scoped_threadpool = "0.1.9"
serde = "1.0.87"
serde_derive = "1.0.87"
structopt = "0.2"
