[package]
name = "map_model"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]

[dependencies]
ordered-float = "0.5.0"
protobuf = "1.4"
rand = "0.5.1"
serde = "1.0"
serde_derive = "1.0"
