[package]
name = "map_model"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
aabb-quadtree = "0.1.0"
abstutil = { path = "../abstutil" }
geom = { path = "../geom" }
gtfs = { path = "../gtfs" }
multimap = "0.4.0"
nbez = "0.1.0"
ordered-float = "1.0.1"
pretty_assertions = "0.5.1"
serde = "1.0.87"
serde_derive = "1.0.87"
