[package]
name = "map_model"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
aabb-quadtree = "0.1.0"
abstutil = { path = "../abstutil" }
fast_paths = { git = "https://github.com/dabreegster/fast_paths" }
geom = { path = "../geom" }
gtfs = { path = "../gtfs" }
nbez = "0.1.0"
petgraph = "0.5.0"
serde = "1.0.89"
serde_derive = "1.0.98"
thread_local = "1.0.1"
seattle_traffic_signals = { git = "https://github.com/dabreegster/seattle_traffic_signals" }
