[package]
name = "map_model"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
aabb-quadtree = "0.1.0"
abstutil = { path = "../abstutil" }
fast_paths = { git = "https://github.com/easbar/fast_paths", rev = "7bdbaf0e02f4dc502a915277d9a079801ce1a752" }
geom = { path = "../geom" }
gtfs = { path = "../gtfs" }
nbez = "0.1.0"
petgraph = "0.4.13"
serde = "1.0.89"
serde_derive = "1.0.98"
thread_local = "0.3.6"
