[package]
name = "map_model"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]

[dependencies]
aabb-quadtree = "0.1.0"
abstutil = { path = "../abstutil" }
dimensioned = { git = "https://github.com/paholg/dimensioned", rev = "0e1076ebfa5128d1ee544bdc9754c948987b6fe3", features = ["serde"] }
flame = "0.2.2"
geo = "0.9.1"
geom = { path = "../geom" }
gtfs = { path = "../gtfs" }
log = "0.4.5"
multimap = "0.4.0"
ordered-float = "0.5.0"
pretty_assertions = "0.5.1"
serde = "1.0"
serde_derive = "1.0"
