[package]
name = "abstutil"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.1.2"
lazy_static = "1.3.0"
rand = { version = "0.6.5", features = ["serde1"] }
rand_xorshift = "0.1.1"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"

[target.'cfg(unix)'.dependencies]
procfs = "0.4.7"
termion = "1.5.1"
