[package]
name = "abstutil"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.1.1"
lazy_static = "1.1.0"
log = "0.4.5"
multimap = "0.4.0"
procfs = "0.4.4"
rand = { version = "0.6.5", features = ["serde1"] }
rand_xorshift = "0.1.1"
serde = "1.0.87"
serde_derive = "1.0"
serde_json = "1.0"
yansi = "0.5.0"
