[package]
name = "abstutil"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.1.0"
log = "0.4.5"
multimap = "0.4.0"
rand = { version = "0.6.4", features = ["serde1"] }
rand_xorshift = "0.1.1"
serde = "1.0"
serde_cbor = "0.9.0"
serde_derive = "1.0"
serde_json = "1.0"
yansi = "0.5.0"
