[package]
name = "editor"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]

[dependencies]
aabb-quadtree = "0.1.0"
control = { path = "../control" }
geom = { path = "../geom" }
ezgui = { path = "../ezgui" }
map_model = { path = "../map_model" }
multimap = "0.4.0"
ordered-float = "0.5.0"
piston = "*"
piston2d-graphics = "*"
piston2d-opengl_graphics = "*"
pistoncore-glutin_window = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sim = { path = "../sim" }
structopt = "0.2"
vecmath = "0.3.1"
