[package]
name = "editor"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]

[dependencies]
aabb-quadtree = "0.1.0"
abstutil = { path = "../abstutil" }
control = { path = "../control" }
counter = "0.4.3"
cpuprofiler = "0.0.3"
dimensioned = { git = "https://github.com/paholg/dimensioned", rev = "0e1076ebfa5128d1ee544bdc9754c948987b6fe3", features = ["serde"] }
downcast = "0.9.2"
ezgui = { path = "../ezgui" }
generator = "0.6"
geo = "0.10.2"
geom = { path = "../geom" }
kml = { path = "../kml" }
lazy_static = "1.1.0"
log = "0.4.5"
map_model = { path = "../map_model" }
piston = "*"
pretty_assertions = "0.5.1"
quick-xml = "0.10.0"
rand = "0.5.1"
serde = "1.0"
serde_derive = "1.0"
sim = { path = "../sim" }
structopt = "0.2"
