[package]
name = "control"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]

[dependencies]
dimensioned = "0.6.0"
map_model = { path = "../map_model" }
serde = "1.0"
serde_derive = "1.0"
