[package]
name = "analyze_code"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
syn = { version = "0.15.24", features = ["parsing", "full", "extra-traits"] }
