[package]
name = "tmp_gfx"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
genmesh = "0.6.2"
glium = "0.23.0"
glutin = "0.19.0"
obj = { version = "0.9", features = ["genmesh"] }
