[package]
name = "ezgui"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
abstutil = { path = "../abstutil" }
geom = { path = "../geom" }
glium = "0.25.1"
glium-glyph = "0.6.0"
glutin = "0.21.0"
nom = "4.2.3"
ordered-float = "1.0.1"
serde = "1.0.89"
serde_derive = "1.0.89"
simsearch = "0.1.4"
textwrap = "0.11"

[target.'cfg(target_os = "linux")'.dependencies]
# TODO Could add gperftools to the Windows Docker image
cpuprofiler = "0.0.3"
