[package]
name = "ezgui"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
abstutil = { path = "../abstutil" }
cpuprofiler = "0.0.3"
geom = { path = "../geom" }
glium = "0.23.0"
glium-glyph = "0.3.0"
glutin = "0.20.0"
palette = "0.4"
serde = "1.0.89"
serde_derive = "1.0.89"
textwrap = "0.11"
