[package]
name = "ezgui"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
abstutil = { path = "../abstutil" }
dimensioned = { git = "https://github.com/paholg/dimensioned", rev = "0e1076ebfa5128d1ee544bdc9754c948987b6fe3", features = ["serde"] }
geom = { path = "../geom" }
log = "0.4.5"
ordered-float = "1.0.1"
palette = "0.4"
piston = "0.39.0"
piston2d-graphics = "0.28.0"
piston2d-opengl_graphics = "0.57.0"
pistoncore-glutin_window = "0.51.1"
screenshot-rs = "0.1.2"
serde = "1.0"
serde_derive = "1.0"
textwrap = "0.11"
