[package]
name = "ezgui"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]

[dependencies]
aabb-quadtree = "0.1.0"
palette = "0.4"
piston = "*"
piston2d-graphics = "*"
piston2d-opengl_graphics = "*"
