name: Build
on: [push]
jobs:
  build-windows:
    runs-on: windows-latest
    if: "contains(github.event.head_commit.message, '[rebuild]')"
    steps:
      - uses: actions/checkout@master
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.40.0
      - name: Run build
        run: cargo build --release --bin game
      - name: Upload binary
        uses: actions/upload-artifact@v1
        with:
          name: game_windows.exe
          path: target/release/game.exe
  build-macos:
    runs-on: macos-latest
    if: "contains(github.event.head_commit.message, '[rebuild]')"
    steps:
      - uses: actions/checkout@master
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.40.0
      - name: Run build
        run: cargo build --release --bin game
      - name: Upload binary
        uses: actions/upload-artifact@v1
        with:
          name: game_mac
          path: target/release/game
  build-linux:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[rebuild]')"
    steps:
      - uses: actions/checkout@master
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.40.0
      - name: Run build
        run: cargo build --release --bin game
      - name: Upload binary
        uses: actions/upload-artifact@v1
        with:
          name: game_linux
          path: target/release/game
